import armadaLogoUrl from '../assets/BGLogoArmada.png'
import { formatPercentage, formatTruck } from '../utils/formatters.js'

function safeFilePart(value) {
  return String(value || 'report')
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase()
}

function formatNumber(value) {
  return (Number(value) || 0).toLocaleString('en-US', {
    minimumFractionDigits: 3,
    maximumFractionDigits: 3,
  })
}

function formatPrintedDate(date = new Date()) {
  return date
    .toLocaleString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    })
    .replace(',', '')
}

function getTodayLabel() {
  return new Date().toISOString().slice(0, 10)
}

function getVesselDisplayName(vesselName) {
  const name = String(vesselName || '-').trim()

  return /^mv\.?\s+/i.test(name) ? name : `MV. ${name}`
}

function getEstimatedTruckRequirement(remainingCargo, averageLoadOverall) {
  const remaining = Number(remainingCargo) || 0
  const averageLoad = Number(averageLoadOverall) || 0

  if (remaining <= 0 || averageLoad <= 0) {
    return null
  }

  return Math.ceil(remaining / averageLoad)
}

function formatTruckRequirement(value) {
  return value ? formatTruck(value) : '-'
}

function getHatchStatus(progressPercentage, overallProgress) {
  const gap = (Number(progressPercentage) || 0) - (Number(overallProgress) || 0)

  if (gap >= -5) return 'Normal'
  if (gap >= -10) return 'Perlu Dipantau'
  if (gap >= -20) return 'Palka Tertinggal'
  return 'Critical'
}

function buildDestinationSummaryTotal(rows) {
  const totalDischarge = rows.reduce((total, row) => total + (Number(row.totalDischarge) || 0), 0)
  const totalDt = rows.reduce((total, row) => total + (Number(row.totalDt) || 0), 0)

  return {
    destination: 'TOTAL',
    totalDischarge,
    totalDt,
    averageTonnage: totalDt > 0 ? totalDischarge / totalDt : 0,
  }
}

async function getImageDataUrl(assetUrl) {
  const response = await fetch(assetUrl)
  const blob = await response.blob()

  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => resolve(String(reader.result || ''))
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

function drawFooter(doc, printedAt) {
  const pageCount = doc.internal.getNumberOfPages()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()

  for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
    doc.setPage(pageNumber)
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(8)
    doc.setTextColor(80, 80, 80)
    doc.text('Generated by Running Discharge Report System', pageWidth - 10, pageHeight - 12, {
      align: 'right',
    })
    doc.text(`Generated at: ${printedAt} WIB`, pageWidth - 10, pageHeight - 7, {
      align: 'right',
    })
  }
}

function drawSummaryCard(doc, { label, value, x, y, width, height }) {
  doc.setDrawColor(215, 222, 232)
  doc.setFillColor(248, 250, 252)
  doc.roundedRect(x, y, width, height, 1.5, 1.5, 'FD')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(6.8)
  doc.setTextColor(60, 82, 112)
  doc.text(String(label || '').toUpperCase(), x + 3, y + 5.5)
  doc.setFontSize(10.5)
  doc.setTextColor(0, 0, 0)
  doc.text(String(value || '-'), x + 3, y + 13)
}

export async function exportRunningReportPDF({
  vessel,
  summary,
  hatchRows,
  destinationSummary,
}) {
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  })
  const printedAt = formatPrintedDate()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 10
  const contentWidth = pageWidth - margin * 2
  const averageLoad = Number(summary?.averageLoadPerTruck) || 0
  const estimatedTruckRequirementTotal = getEstimatedTruckRequirement(
    summary?.totalRemaining,
    averageLoad,
  )

  try {
    const logoDataUrl = await getImageDataUrl(armadaLogoUrl)
    doc.addImage(logoDataUrl, 'PNG', margin + 3, 8, 28, 20)
  } catch (_error) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.text('ARMADA', margin, 16)
  }

  doc.setTextColor(20, 20, 20)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('ARMADA GROUP', pageWidth / 2, 11, { align: 'center' })
  doc.setFontSize(12)
  doc.text(getVesselDisplayName(vessel?.vesselName), pageWidth / 2, 18, { align: 'center' })
  doc.setFontSize(13)
  doc.setTextColor(150, 0, 0)
  doc.text('RUNNING DISCHARGE RESULT', pageWidth / 2, 26, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.text(`Printed preview: ${printedAt}`, pageWidth / 2, 32, { align: 'center' })

  const tableTheme = {
    theme: 'grid',
    styles: {
      font: 'helvetica',
      fontSize: 7.6,
      cellPadding: 2.1,
      lineColor: [215, 222, 232],
      lineWidth: 0.15,
      textColor: [10, 24, 48],
    },
    headStyles: {
      fillColor: [235, 238, 242],
      textColor: [10, 24, 48],
      fontStyle: 'bold',
      halign: 'center',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  }

  const cardGap = 3
  const cardWidth = (contentWidth - cardGap * 2) / 3
  const cardHeight = 16
  const cardStartY = 42
  const summaryCards = [
    ['Total Cargo', formatNumber(summary?.totalCargo)],
    ['Total Discharge', formatNumber(summary?.totalDischarge)],
    ['Remaining Cargo', formatNumber(summary?.totalRemaining)],
    ['Progress %', formatPercentage(summary?.overallProgress)],
    ['Total Truck', formatTruck(summary?.totalTruck)],
    ['Average Load', formatNumber(averageLoad)],
  ]

  summaryCards.forEach(([label, value], index) => {
    const row = Math.floor(index / 3)
    const column = index % 3

    drawSummaryCard(doc, {
      label,
      value,
      x: margin + column * (cardWidth + cardGap),
      y: cardStartY + row * (cardHeight + 3),
      width: cardWidth,
      height: cardHeight,
    })
  })

  const hatchBody = (hatchRows || []).map((row) => {
    const estimatedTruckRequirement = getEstimatedTruckRequirement(row.remainingOnBoard, averageLoad)

    return [
      row.hatch || '-',
      formatNumber(row.finalStowage),
      formatNumber(row.totalDischarge),
      formatNumber(row.remainingOnBoard),
      formatPercentage(row.progressPercentage),
      getHatchStatus(row.progressPercentage, summary?.overallProgress),
      formatTruck(row.totalTruck),
      formatTruckRequirement(estimatedTruckRequirement),
    ]
  })

  hatchBody.push([
    'TOTAL',
    formatNumber(summary?.totalCargo),
    formatNumber(summary?.totalDischarge),
    formatNumber(summary?.totalRemaining),
    formatPercentage(summary?.overallProgress),
    '-',
    formatTruck(summary?.totalTruck),
    formatTruckRequirement(estimatedTruckRequirementTotal),
  ])

  autoTable(doc, {
    ...tableTheme,
    startY: cardStartY + cardHeight * 2 + 12,
    head: [[
      'Hatch',
      'Initial Cargo',
      'Discharge',
      'Remaining',
      'Progress %',
      'Status',
      'Total Truck',
      'Est. Truck Requirement',
    ]],
    body: hatchBody,
    columnStyles: {
      0: { halign: 'left' },
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right' },
      5: { halign: 'left' },
      6: { halign: 'right' },
      7: { halign: 'right' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.row.index === hatchBody.length - 1) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.fillColor = [235, 238, 242]
      }
    },
    margin: { left: margin, right: margin },
  })

  const lowerStartY = doc.lastAutoTable.finalY + 8
  const lowerGap = 6
  const halfWidth = (contentWidth - lowerGap) / 2

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)
  doc.text('Additional Calculation', margin, lowerStartY)
  doc.text('Destination Summary', margin + halfWidth + lowerGap, lowerStartY)
  doc.setDrawColor(230, 235, 242)
  doc.line(margin, lowerStartY + 5, margin + halfWidth, lowerStartY + 5)
  doc.line(
    margin + halfWidth + lowerGap,
    lowerStartY + 5,
    margin + halfWidth * 2 + lowerGap,
    lowerStartY + 5,
  )

  autoTable(doc, {
    ...tableTheme,
    startY: lowerStartY + 8,
    head: [['Description', 'Value']],
    body: [
      ['Average Load / Truck', formatNumber(averageLoad)],
      ['Est. Truck Requirement', formatTruckRequirement(estimatedTruckRequirementTotal)],
    ],
    columnStyles: {
      0: { halign: 'left' },
      1: { halign: 'right' },
    },
    tableWidth: halfWidth,
    margin: { left: margin, right: pageWidth - margin - halfWidth },
  })

  const destinationRows = destinationSummary?.length
    ? destinationSummary
    : []
  const destinationTotal = buildDestinationSummaryTotal(destinationRows)
  const destinationBody = destinationRows.map((row) => [
    row.destination || '-',
    formatNumber(row.totalDischarge),
    formatTruck(row.totalDt),
    formatNumber(row.averageTonnage),
  ])

  destinationBody.push([
    destinationTotal.destination,
    formatNumber(destinationTotal.totalDischarge),
    formatTruck(destinationTotal.totalDt),
    formatNumber(destinationTotal.averageTonnage),
  ])

  autoTable(doc, {
    ...tableTheme,
    startY: lowerStartY + 8,
    head: [['Destination', 'Netto', 'DT', 'Average']],
    body: destinationRows.length
      ? destinationBody
      : [['-', formatNumber(0), formatTruck(0), formatNumber(0)]],
    columnStyles: {
      0: { halign: 'left' },
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'right' },
    },
    didParseCell: (data) => {
      if (destinationRows.length && data.section === 'body' && data.row.index === destinationBody.length - 1) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.fillColor = [235, 238, 242]
      }
    },
    tableWidth: halfWidth,
    margin: { left: margin + halfWidth + lowerGap, right: margin },
  })

  drawFooter(doc, printedAt)
  doc.save(`running-report-${safeFilePart(vessel?.vesselName)}-${getTodayLabel()}.pdf`)
}
